import './globals.css'
import { Inter } from 'next/font/google'
import Header from "@/components/Header";
import {ThemeProvider} from "@/components/ThemeProvider";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'NEXT | Coins | m4xx1k',
  description: 'Generated by create next app. Author - m4xx1k',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-light dark:bg-dark text-dark dark:text-light transition-colors duration-500`}>
      <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <Header/>
          {children}
      </ThemeProvider>
      </body>
    </html>
  )
}
