import './globals.css'
import { Inter } from 'next/font/google'
import Header from "@/components/Header";

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Crypto | m4xx1k',
  description: 'Generated by create next app. Author - m4xx1k',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${inter.className} bg-zinc-900`}>
      <Header/>
      {children}
      </body>
    </html>
  )
}
